version: '3.9'

services:
  web:
    build: .
    container_name: travels_backend
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - travels_db_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  travels_db_postgres_data:
